services:
  kvs-node1:                       # create a node called kvs-node
    image: kvs:latest             # specify image
    environment:                  # set env vars
      - ADDRESS=10.10.0.2:8080
    ports:                        # same as the -p flag
      - "8080:8080"
    networks:                     # use network called kvs-subnet
      kvs-subnet:
        ipv4_address: 10.10.0.2   # define the address in that subnet
  kvs-node2:                       # create a node called kvs-node
    image: kvs:latest             # specify image
    environment:                  # set env vars
      - ADDRESS=10.10.0.3:8080
    ports:                        # same as the -p flag
      - "8081:8080"
    networks:                     # use network called kvs-subnet
      kvs-subnet:
        ipv4_address: 10.10.0.3   # define the address in that subnet
  kvs-node3:                       # create a node called kvs-node
    image: kvs:latest             # specify image
    environment:                  # set env vars
      - ADDRESS=10.10.0.4:8080
    ports:                        # same as the -p flag
      - "8082:8080"
    networks:                     # use network called kvs-subnet
      kvs-subnet:
        ipv4_address: 10.10.0.4   # define the address in that subnet
  
  kvs-node4:                       # create a node called kvs-node
    image: kvs:latest             # specify image
    environment:                  # set env vars
      - ADDRESS=10.10.0.5:8080
    ports:                        # same as the -p flag
      - "8083:8080"
    networks:                     # use network called kvs-subnet
      kvs-subnet:
        ipv4_address: 10.10.0.5   # define the address in that subnet
  kvs-node5:                       # create a node called kvs-node
    image: kvs:latest             # specify image
    environment:                  # set env vars
      - ADDRESS=10.10.0.6:8080
    ports:                        # same as the -p flag
      - "8084:8080"
    networks:                     # use network called kvs-subnet
      kvs-subnet:
        ipv4_address: 10.10.0.6   # define the address in that subnet
  kvs-node6:                       # create a node called kvs-node
    image: kvs:latest             # specify image
    environment:                  # set env vars
      - ADDRESS=10.10.0.7:8080
    ports:                        # same as the -p flag
      - "8085:8080"
    networks:                     # use network called kvs-subnet
      kvs-subnet:
        ipv4_address: 10.10.0.7   # define the address in that subnet

networks:
  kvs-subnet:                      # create a network called kvs-subnet
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16    # use subnet 10.10.0.0 with a 16 bit mask
